# Generated by Django 6.0.4 on 2026-07-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('est_interne', models.BooleanField(default=False, help_text="Coche cette case pour les dépôts internes (ex. 'M/M' dans le fichier Excel). Ces dépôts sont automatiquement considérés comme soldés, sans paiement réel.")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_incubation_jours', models.PositiveIntegerField(help_text="Nombre de jours entre le dépôt et l'éclosion prévue (DPE).")),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_especes/')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('activee_le', models.DateTimeField(blank=True, null=True)),
                ('identifiant_machine', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
            },
        ),
        migrations.CreateModel(
            name='MediaBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('fichier', models.ImageField(upload_to='bibliotheque/')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image (bibliothèque)',
                'verbose_name_plural': 'Images (bibliothèque)',
                'ordering': ['-ajoute_le'],
            },
        ),
        migrations.CreateModel(
            name='ParametresApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='Ma Couveuse', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('fond_ecran', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('jours_avant_mirage', models.PositiveIntegerField(default=7, help_text='Correspond à la formule DM = Date de dépôt + N jours.')),
                ('seuil_alerte_jours', models.PositiveIntegerField(default=3, help_text="Seuil de la mise en forme conditionnelle Excel (Jrs R. <= 3). Un dépôt est signalé en alerte 'éclosion proche' sous ce seuil.")),
            ],
            options={
                'verbose_name': "Paramètres de l'application",
                'verbose_name_plural': "Paramètres de l'application",
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateField(verbose_name='Date de dépôt')),
                ('quantite', models.PositiveIntegerField(verbose_name='Qté')),
                ('resultat_mirage', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (restant après mirage)')),
                ('date_mirage_effectue', models.DateField(blank=True, null=True)),
                ('nombre_eclos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Éclos')),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acompte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rem (acompte)')),
                ('paiement_solde', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payé (solde)')),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='core.client')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='core.espece')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'ordering': ['-date_depot'],
                'indexes': [models.Index(fields=['date_depot'], name='core_depot_date_de_9a2415_idx')],
            },
        ),
    ]
