# Generated by Django 6.0.4 on 2026-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_depot_remise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediabibliotheque',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parametresapplication',
            options={'verbose_name': 'Paramètres', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.RemoveIndex(
            model_name='depot',
            name='core_depot_date_de_9a2415_idx',
        ),
        migrations.AddField(
            model_name='depot',
            name='date_eclosion_effectuee',
            field=models.DateField(blank=True, null=True, verbose_name='Date réelle éclosion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='est_interne',
            field=models.BooleanField(default=False, help_text='Client interne (M/M), les dépôts sont considérés comme soldés.'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depot',
            name='date_mirage_effectue',
            field=models.DateField(blank=True, null=True, verbose_name='Date réelle mirage'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='paiement_solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depot',
            name='resultat_mirage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='parametresapplication',
            name='jours_avant_mirage',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='parametresapplication',
            name='seuil_alerte_jours',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
